add dto
TonyH277/online-book-store pull request #2
Opened 2024-04-22 13:34 UTC by TonyH277

2024-04-22 19:22 UTC, MolchanovAlexander approved these changes

2024-04-22 19:22 UTC, MolchanovAlexander commented on src/main/java/mate/academy/bookshop/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(savedBook);
I did the same but in 1 line .

2024-04-23 07:40 UTC, karma-o requested changes
Left a minor comments

2024-04-23 07:40 UTC, karma-o commented on src/main/java/mate/academy/bookshop/repository/impl/BookRepositoryImpl.java
> +                    .uniqueResultOptional();
I am sure there is a better method like `find()` or something like that to not use a `createQuery()`

2024-04-23 07:40 UTC, karma-o commented on src/main/java/mate/academy/bookshop/dto/BookDto.java
> +@Component
why would we need to mark DTO classes with a `@Component`?
Components are usually services, util classes, and other stuff like this, but never a POJO/DTO classes

2024-04-23 07:40 UTC, karma-o commented on src/main/java/mate/academy/bookshop/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(savedBook);
space used is not always better, I personally would prefer a more readable solution over a more concise one 😉
this solution looks just fine as for me. 
But of course in some places we really can do things very short and pretty and that is the thing we should all strive for

2024-04-23 09:40 UTC, yevheniisynytsia approved these changes
Great job! Please fix the comments I left. They are minor that's why I approve

2024-04-23 09:40 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookshop/config/MapperConfig.java
> +)
```suggestion
        implementationPackage = "<PACKAGE_NAME>.impl")
```

2024-04-23 09:40 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookshop/controller/BookController.java
> +@AllArgsConstructor
```suggestion
@RequiredArgsConstructor
```

2024-04-23 09:40 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookshop/controller/BookController.java
> +@AllArgsConstructor
this will take only `final` fields as the constructor params. Let's imagine you'll have a string here, that you use only here and don't want it to be passed to the class via constructor. In this case `@AllArgs` will have 2 params, and `@RequiredArgs` will have only BookService

2024-04-23 09:40 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookshop/repository/impl/BookRepositoryImpl.java
> +@AllArgsConstructor
same here, `@RequiredArgs` is used as a standard for services as they usually have fields marked as `final`

2024-04-23 11:54 UTC, merged