add JPA Repository to project & add put, delete endpoints
TonyH277/online-book-store pull request #3
Opened 2024-04-24 15:26 UTC by TonyH277

2024-04-24 18:24 UTC, ReamFOX approved these changes
LGTM. Just one comment.

2024-04-24 18:24 UTC, ReamFOX commented on src/main/java/mate/academy/bookshop/model/Book.java
> +@Where(clause = "is_deleted=false")
@Where is Deprecated, use this instead.
```suggestion
@SQLRestriction("is_deleted=false")
```

2024-04-25 09:12 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookshop/model/Book.java
> +@Where(clause = "is_deleted=false")
++

2024-04-25 09:20 UTC, yevheniisynytsia requested changes
GJ! Left minor comment

2024-04-25 09:20 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +      id: 1
let's give it a name like `create-books-table`

2024-04-25 09:20 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +      id: 1
instead of `1`

2024-04-25 09:20 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/02-add-soft-delete-to-book-table.yaml
> +      id: 2
same here

2024-04-25 09:20 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/02-add-soft-delete-to-book-table.yaml
> +      id: 2
this could be done in one changeset, but it's ok also

2024-04-25 13:34 UTC, andrii-hoienko approved these changes
Good job!

2024-04-26 11:09 UTC, merged