Pagination sorting swagger
TonyH277/online-book-store pull request #6
Opened 2024-05-01 07:18 UTC by TonyH277

2024-05-01 14:03 UTC, vikkushnir requested changes
GJ! But you can delete methods from BookRepository, and your app will work the same, what about searchBooks and Pageable only if you wish:)

2024-05-01 14:03 UTC, vikkushnir commented on src/main/java/mate/academy/bookshop/repository/book/BookRepository.java
> +    List<Book> findAll(Sort sort);
These methods are redundant, in case you are using JpaRepository, Pageable, and Sort will be working even without them

2024-05-01 14:03 UTC, vikkushnir commented on src/main/java/mate/academy/bookshop/controller/BookController.java
>      public List<BookDto> searchBooks(BookSearchParametersDto searchParameters) {
you can also add Pageable to this method

2024-05-02 13:35 UTC, andrii-hoienko requested changes
Nice, left minor comments

2024-05-02 13:35 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookshop/controller/BookController.java
>      public List<BookDto> searchBooks(BookSearchParametersDto searchParameters) {
agree

2024-05-02 13:35 UTC, andrii-hoienko commented on pom.xml
> +            <version>2.5.0</version>
Please use variables to define versions as you did before

2024-05-03 14:07 UTC, merged