security init commit
TonyH277/online-book-store pull request #8
Opened 2024-05-09 19:54 UTC by TonyH277

2024-05-10 07:31 UTC, makaroshyna requested changes
Good job! Just some minor comments here.

2024-05-10 07:31 UTC, makaroshyna commented on src/main/java/mate/academy/bookshop/config/security/SecurityConfig.java
> +                                .requestMatchers("/auth/**", "/error")
I think we should put "/swagger-ui/**" here too.

2024-05-10 07:31 UTC, makaroshyna commented on src/main/java/mate/academy/bookshop/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
I think Admin should be able to get all books.

2024-05-10 07:31 UTC, makaroshyna commented on src/main/java/mate/academy/bookshop/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
And here too, why shouldn't admin have an access to get endpoints?

2024-05-10 07:31 UTC, makaroshyna commented on src/main/java/mate/academy/bookshop/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
The same here.

2024-05-10 07:31 UTC, makaroshyna commented on src/main/java/mate/academy/bookshop/model/User.java
> +    private boolean isDeleted;
```suggestion
    private boolean isDeleted = false;
```

2024-05-10 07:31 UTC, makaroshyna commented on src/main/java/mate/academy/bookshop/model/User.java
> +
I think you should also add getPassword() here.

2024-05-14 11:25 UTC, vovasalyha approved these changes

2024-05-14 11:25 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/06-create-users-roles-join-table.yaml
> +            tableName: users_roles
Make user_id + role_id a composite primary key to disallow duplicate entries.

2024-05-15 06:23 UTC, merged