add jwt authentication
TonyH277/online-book-store pull request #9
Opened 2024-05-13 06:37 UTC by TonyH277

2024-05-14 12:35 UTC, d1sam requested changes
Good job, but there are some minor changes, that should be done according my comments.

2024-05-14 12:35 UTC, d1sam commented on src/main/java/mate/academy/bookshop/controller/AuthenticationController.java
> +    @PostMapping("login")
```suggestion
    @PostMapping("/login")
```

2024-05-14 12:35 UTC, d1sam commented on src/main/java/mate/academy/bookshop/controller/AuthenticationController.java
> +    @PostMapping("login")
what about swagger? response status?

2024-05-14 12:35 UTC, d1sam commented on src/main/java/mate/academy/bookshop/dto/UserLoginRequestDto.java
> +        String password) {
let's validate the size also

2024-05-14 12:35 UTC, d1sam commented on src/main/java/mate/academy/bookshop/dto/UserLoginRequestDto.java
> +        @NotBlank(message = "can not be blank")
let's validate the size also

2024-05-14 12:35 UTC, d1sam commented on src/main/resources/application.properties
> +jwt.secret=dpas0-dik-a90jdf09gh903r032opnpfsad{}320rjnsf/>OPJ/f
let's provide these values from env properties

2024-05-15 10:37 UTC, vovasalyha approved these changes
Approving, but left few comments for consideration.

2024-05-15 10:37 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/config/security/SecurityConfig.java
>                  .build();
For JWT security it's also good to make a session management stateless.

2024-05-15 10:37 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/controller/AuthenticationController.java
> +    @ResponseStatus(HttpStatus.OK)
200 is a default status, it's not necessary to specify it.

2024-05-15 10:37 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/util/JwtUtil.java
> +            throw new JwtException("Expired or invalid JWT token");
```suggestion
            return false;
```

2024-05-15 11:21 UTC, merged